# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/LineLength:
  Enabled: true
  Max: 70
  AllowURI: false
  AllowedPatterns: []

Metrics/BlockNesting:
  Enabled: true
  Max: 3
  CountBlocks: false
  CountModifierForms: true

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
