FROM ruby:3.4.6-slim
RUN apt-get update -qq && apt-get install --no-install-recommends -y build-essential libpq-dev libyaml-dev git curl chromium chromium-driver && rm -rf /var/lib/apt/lists/*
WORKDIR /app
